//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionType
    {
        public CompetitionType()
        {
            this.CupCompetitionType = new HashSet<CupCompetitionType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdWeaponType { get; set; }
        public Nullable<int> SeriesCount { get; set; }
    
        public virtual WeaponTypes WeaponTypes { get; set; }
        public virtual ICollection<CupCompetitionType> CupCompetitionType { get; set; }
    }
}
