//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetitionType
    {
        public CompetitionType()
        {
            this.CupCompetitionType = new HashSet<CupCompetitionType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int IdWeaponType { get; set; }
        public Nullable<int> SeriesCount { get; set; }
    
        public virtual WeaponTypes WeaponTypes { get; set; }
        public virtual ICollection<CupCompetitionType> CupCompetitionType { get; set; }
    }
}
