//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.Regions = new HashSet<Regions>();
        }
    
        public int Id { get; set; }
        public string CODE { get; set; }
        public string CountryName { get; set; }
    
        public virtual ICollection<Regions> Regions { get; set; }
    }
}
