//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupCompetitionType
    {
        public CupCompetitionType()
        {
            this.EntryForCompetitions = new HashSet<EntryForCompetitions>();
            this.Results = new HashSet<Results>();
        }
    
        public int Id { get; set; }
        public int IdCup { get; set; }
        public int IdCompetitionType { get; set; }
        public Nullable<System.DateTime> TimeFirstShift { get; set; }
    
        public virtual CompetitionType CompetitionType { get; set; }
        public virtual Cups Cups { get; set; }
        public virtual ICollection<EntryForCompetitions> EntryForCompetitions { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
