//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CupCompetitionType
    {
        public CupCompetitionType()
        {
            this.EntryForCompetitions = new HashSet<EntryForCompetitions>();
            this.Results = new HashSet<Results>();
        }
    
        public int Id { get; set; }
        public int IdCup { get; set; }
        public int IdCompetitionType { get; set; }
        public Nullable<System.DateTime> TimeFirstShift { get; set; }
    
        public virtual CompetitionType CompetitionType { get; set; }
        public virtual Cups Cups { get; set; }
        public virtual ICollection<EntryForCompetitions> EntryForCompetitions { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
