//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cups
    {
        public Cups()
        {
            this.CupCompetitionType = new HashSet<CupCompetitionType>();
        }
    
        public int IdCup { get; set; }
        public string Name { get; set; }
        public int IdCupType { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public int IdShootingRange { get; set; }
        public byte[] Document { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual CupTypes CupTypes { get; set; }
        public virtual ICollection<CupCompetitionType> CupCompetitionType { get; set; }
        public virtual ShootingRanges ShootingRanges { get; set; }
        public virtual Users Users { get; set; }
    }
}
