//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShootingCompetitionRequestsEntities : DbContext
    {
        public ShootingCompetitionRequestsEntities()
            : base("name=ShootingCompetitionRequestsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompetitionType> CompetitionType { get; set; }
        public DbSet<Countries> Countries { get; set; }
        public DbSet<CupCompetitionType> CupCompetitionType { get; set; }
        public DbSet<Cups> Cups { get; set; }
        public DbSet<CupTypes> CupTypes { get; set; }
        public DbSet<EntryForCompetitions> EntryForCompetitions { get; set; }
        public DbSet<EntryStatus> EntryStatus { get; set; }
        public DbSet<RecoveredPasswords> RecoveredPasswords { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<Results> Results { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<ShooterCategory> ShooterCategory { get; set; }
        public DbSet<ShooterClubs> ShooterClubs { get; set; }
        public DbSet<Shooters> Shooters { get; set; }
        public DbSet<ShootingRanges> ShootingRanges { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WeaponTypes> WeaponTypes { get; set; }
    }
}
