//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryForCompetitions
    {
        public int Id { get; set; }
        public int IdShooter { get; set; }
        public int IdCupCompetitionType { get; set; }
        public System.DateTime DateCreate { get; set; }
        public int IdEntryStatus { get; set; }
    
        public virtual CupCompetitionType CupCompetitionType { get; set; }
        public virtual EntryStatus EntryStatus { get; set; }
        public virtual Shooters Shooters { get; set; }
    }
}
