//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecoveredPasswords
    {
        public int Id { get; set; }
        public string Password { get; set; }
        public int IdUser { get; set; }
        public bool IsRecovered { get; set; }
        public System.DateTime ActionDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
