//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regions
    {
        public Regions()
        {
            this.ShootingRanges = new HashSet<ShootingRanges>();
        }
    
        public int IdRegion { get; set; }
        public string Name { get; set; }
        public string FederationAddress { get; set; }
        public string FederationTelefon { get; set; }
        public int IdCountry { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual ICollection<ShootingRanges> ShootingRanges { get; set; }
    }
}
