//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shooters
    {
        public Shooters()
        {
            this.EntryForCompetitions = new HashSet<EntryForCompetitions>();
            this.Results = new HashSet<Results>();
        }
    
        public int IdShooter { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public int IdClub { get; set; }
        public string Address { get; set; }
        public int IdCategory { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int IdWeaponType { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Sex { get; set; }
    
        public virtual ICollection<EntryForCompetitions> EntryForCompetitions { get; set; }
        public virtual ShooterCategory ShooterCategory { get; set; }
        public virtual WeaponTypes WeaponTypes { get; set; }
        public virtual ShooterClubs ShooterClubs { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Results> Results { get; set; }
    }
}
