//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShooterClubs
    {
        public ShooterClubs()
        {
            this.Shooters = new HashSet<Shooters>();
        }
    
        public int IdClub { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string MainCoach { get; set; }
        public int IdShootingRange { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual ShootingRanges ShootingRanges { get; set; }
        public virtual ICollection<Shooters> Shooters { get; set; }
        public virtual Users Users { get; set; }
    }
}
