//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShooterCategory
    {
        public ShooterCategory()
        {
            this.Shooters = new HashSet<Shooters>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Keychar { get; set; }
        public int OrderSort { get; set; }
    
        public virtual ICollection<Shooters> Shooters { get; set; }
    }
}
