//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShootingRanges
    {
        public ShootingRanges()
        {
            this.Cups = new HashSet<Cups>();
            this.ShooterClubs = new HashSet<ShooterClubs>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Telefon { get; set; }
        public string Info { get; set; }
        public int IdRegion { get; set; }
        public string Town { get; set; }
        public int IdUser { get; set; }
    
        public virtual ICollection<Cups> Cups { get; set; }
        public virtual ICollection<ShooterClubs> ShooterClubs { get; set; }
        public virtual Users Users { get; set; }
        public virtual Regions Regions { get; set; }
    }
}
