//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shooters
    {
        public Shooters()
        {
            this.EntryForCompetitions = new HashSet<EntryForCompetitions>();
            this.Results = new HashSet<Results>();
        }
    
        public int IdShooter { get; set; }
        public string Family { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public int IdClub { get; set; }
        public string Address { get; set; }
        public int IdCategory { get; set; }
        public System.DateTime BirthDate { get; set; }
        public int IdWeaponType { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool Sex { get; set; }
    
        public virtual ICollection<EntryForCompetitions> EntryForCompetitions { get; set; }
        public virtual ICollection<Results> Results { get; set; }
        public virtual ShooterCategory ShooterCategory { get; set; }
        public virtual ShooterClubs ShooterClubs { get; set; }
        public virtual Users Users { get; set; }
        public virtual WeaponTypes WeaponTypes { get; set; }
    }
}
