//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Cups = new HashSet<Cups>();
            this.RecoveredPasswords = new HashSet<RecoveredPasswords>();
            this.ShooterClubs = new HashSet<ShooterClubs>();
            this.Shooters = new HashSet<Shooters>();
            this.ShootingRanges = new HashSet<ShootingRanges>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string FatherName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string E_mail { get; set; }
    
        public virtual ICollection<Cups> Cups { get; set; }
        public virtual ICollection<RecoveredPasswords> RecoveredPasswords { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<ShooterClubs> ShooterClubs { get; set; }
        public virtual ICollection<Shooters> Shooters { get; set; }
        public virtual ICollection<ShootingRanges> ShootingRanges { get; set; }
    }
}
