//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeaponTypes
    {
        public WeaponTypes()
        {
            this.CompetitionType = new HashSet<CompetitionType>();
            this.Shooters = new HashSet<Shooters>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string KeyChar { get; set; }
    
        public virtual ICollection<CompetitionType> CompetitionType { get; set; }
        public virtual ICollection<Shooters> Shooters { get; set; }
    }
}
